### ISSUE TITLE
Build failure: tuxguitar-gtk-integration

### ISSUE THREAD

**Issue by hejops** [cyclopsian/tuxguitar#5]
Sorry if this is a dumb question, I'm not familiar with building java. I've followed the build instructions for "Generic GNU/Linux", but the build fails as follows:

```
...
[INFO] tuxguitar-oss ...................................... SUCCESS [  0.019 s]
[INFO] tuxguitar-oss-linux-x86_64 ......................... SUCCESS [  0.914 s]
[INFO] tuxguitar-fluidsynth ............................... SUCCESS [  0.025 s]
[INFO] tuxguitar-fluidsynth-linux-x86_64 .................. SUCCESS [  0.920 s]
[INFO] tuxguitar-gtk-integration .......................... FAILURE [  0.161 s]
[INFO] tuxguitar-gtk-integration-linux-x86_64 ............. SKIPPED
[INFO] tuxguitar-linux-x86_64 ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.743 s
[INFO] Finished at: 2020-08-15T01:25:05+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project tuxguitar-gtk-integration: Compilation failure
[ERROR] javac: invalid target release: 9
[ERROR] Usage: javac <options> <source files>
[ERROR] use -help for a list of possible options
```

I'm using `javac 1.8.0_262` and `Apache Maven 3.6.3`. How should I fix this?

**Comment by JCGoran** [comment]
A possible workaround is to not build `gtk-integration` in the first place - note that the final build is then not going to have the native window header as mentioned in the README, but no other features should be affected or missing.

I'm attaching a patch below, you can save it to your computer, and then apply it using `git apply [path/to/patch_file]`. After this, just re-run the build command.

[disable_build_gtk_integration.txt](https://github.com/cyclopsian/tuxguitar/files/5252483/disable_build_gtk_integration.txt)

**Comment by hejops** [comment]
Thank you, the patch worked nicely.
